title: MUST-SEE-JAPAN
description: vote your favorite place JAPAN
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vT2DHhipUebpE47Hfe5CxZysVXaJvt98BiRGuP1j5CZhKiRy2yJBDEfRyb65hvtcQICoriUR9CRITGf/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#d2691e"
orderby: distance
