title: MUST-SEE-JAPAN
description: vote your favorite place JAPAN
data_url: https://docs.google.com/spreadsheets/d/1-CPCKa1E3sCRjBs9DUhdmi9nRnXRlyG9vgIqKbHe7UM/edit?usp=sharing
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#d2691e"
orderby: distance
